### ISSUE TITLE
Update to work for all use cases

### ISSUE THREAD

**Issue by zachthedev** [nvonbulow/hangouts-converter#2]
With the announcement of the death of Google Hangouts (or at least the death of Hangouts Classic, it will be transferred to Hangouts Chat), I would love to use this application to get away from hangouts and convert all of my Hangouts SMS to Messages using sms backup and restore. As I am coming off of Google Voice and onto Google Fi, I know this tool would be extremely useful as there are many more people that have my same problem.

**Comment by nvonbulow** [comment]
@Zangoran That's actually a good idea, but it looks like the Google Voice data is provided in an HTML format, so that will be more work than fixing #1. I am also looking to add full MMS support at some point which embeds the images into the backup rather than using a link.

For now, however, I don't have the time as I am a full-time student. I will see what I can do over the holidays in a couple weeks' time.

**Comment by zachthedev** [comment]
I think just doing Hangouts to SMS backup and restore is important. Because people can still use the google voice app. It's mainly for people that had Google Voice and used Hangouts as their SMS app.
Whenever you have a chance to fix it, that would be wonderful! I found this [app](https://github.com/paulwardrip/GoogleExportSMS), that seems to work except it exceptions out at the end.
